Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BBlog.Models
{
    public class Contact
    {
        [Key]
        [Required (ErrorMessage="Name cannot be blank")]
        public string Name { get; set; }
        [Required (ErrorMessage="Email cannot be blank")]
        public string Email { get; set; }
        [Required (ErrorMessage="Subject cannot be blank")]
        public string Subject { get; set; }
    }
}

Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BBlog.DB;
using BBlog.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace BBlog.Controllers
{
    public class BlogController : Controller
    {
        private readonly ILogger<BlogController> _logger;
        private readonly ProgramDbContext _context;
        public BlogController(ILogger<BlogController> logger,ProgramDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            if(Request.Cookies["Username"]=="bangddh06052001")
            {
                return View();
            }
            return Redirect("/Home/Login");
        }
        [HttpPost]
        public IActionResult CreateBlog(BlogInfo blogInfo, IFormFile imageFile)
        {
                if(imageFile!=null){
                    string ImageName = $"id_{blogInfo.BlogTitle}" + Path.GetExtension(imageFile.FileName);
                    //Get url To Save
                    string saveRelativePath = $"/Image/BlogImage";

                    string savePath = Directory.GetCurrentDirectory().Replace("\\", "/") + "/wwwroot" + saveRelativePath + ImageName;

                    Directory.CreateDirectory(Path.GetDirectoryName(savePath));

                    using (var stream = new FileStream(savePath, FileMode.Create))
                    {
                        imageFile.CopyTo(stream);
                    }
                    blogInfo.BlogImage = saveRelativePath + ImageName;
                }
                _context.BlogInfos.Add(blogInfo);
                _context.SaveChanges();
            return Redirect("/Home/Index");
        }
        public IActionResult ManageBlog()
        {
            if(Request.Cookies["Username"]=="bangddh06052001")
            {
                IEnumerable<BlogInfo> listblog = this._context.BlogInfos;
                return View(listblog);
            }
            return Redirect("/Home/Login");
        }
        [HttpGet]
        public IActionResult DeleteBlog(int blogID)
        {
            if(Request.Cookies["Username"]=="bangddh06052001")
            {
                BlogInfo b = _context.BlogInfos.Find(blogID);
                _context.BlogInfos.Remove(b);
                _context.SaveChanges();
                return Redirect("/Blog/ManageBlog");
            }
            return Redirect("/Home/Login");
        }
        
        public IActionResult BlogDetail(int blogID)
        {
            BlogInfo b = _context.BlogInfos.Find(blogID);
            ViewData["LoginUserName"] = Request.Cookies["Username"];
            ViewData["Comments"] = _context.BlogComments.Where(item => item.BlogID == blogID).ToList();
            return View(b);
        }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BBlog.DB;
using BBlog.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace BBlog.Controllers
{
    public class ContactController : Controller
    {
        private readonly ILogger<BlogController> _logger;
        private readonly ProgramDbContext _context;
        public ContactController(ILogger<BlogController> logger,ProgramDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult Index()
        {
            if(Request.Cookies["Username"]!=null){
            string username = Request.Cookies["Username"]; 
            if(_context.Users.Find(username).isAdmin==true)
            {
                IEnumerable<Contact> listContact = this._context.Contacts;
                return View(listContact);
            }
            }
            return NotFound();
        }
        
        public IActionResult CreateContact(Contact contact)
        {
            if(ModelState.IsValid){
                _context.Contacts.Add(contact);
                _context.SaveChanges();
            }
            return Redirect("/Home/Index");
        }
        public IActionResult UpdateContact(Contact contact)
        {
            if(ModelState.IsValid){
                _context.Contacts.Update(contact);
                _context.SaveChanges();
            }
            return Redirect("/Contact/Index");
        }
        public IActionResult DeleteContact(int contactID)
        {
            if(contactID != null){
                Contact c = _context.Contacts.Find(contactID);
                _context.Contacts.Add(c);
                _context.SaveChanges();
            }
            return Redirect("/Contact/Index");
        }
        public IActionResult UpdateStatus(string name)
        {
            if(name != null){
                Contact c = _context.Contacts.Find(name);
                _context.Contacts.Update(c);
                _context.SaveChanges();
            }
            return Redirect("/Contact/Index");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BBlog.Models;
using BBlog.DB;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Extensions.Configuration;
using System.IO;
using Microsoft.AspNetCore.Authentication.Facebook;
using Facebook;
using System.Web;
using Microsoft.AspNetCore.Http;

namespace BBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        string appid = string.Empty;
        string appsecret = string.Empty;

        private readonly ProgramDbContext _context;


        public HomeController(ILogger<HomeController> logger, ProgramDbContext context)
        {
            _context = context;

            _logger = logger;
            var configuration = GetConfiguration();
            appid = configuration.GetSection("AppID").Value;
            appsecret = configuration.GetSection("AppSecret").Value;


        }
        public IConfiguration GetConfiguration()
        {
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
            return builder.Build();
        }
        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Headers["Referer"].ToString());
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }
        [HttpGet]
        public IActionResult Facebook()
        {
            var fb = new FacebookClient();

            var loginurl = fb.GetLoginUrl(new
            {
                client_id = appid,
                client_secret = appsecret,

                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email"
            });
            return Redirect(loginurl.AbsoluteUri);
        }
        public IActionResult FacebookCallbackAsync(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = appid,
                client_secret = appsecret,
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });
            var accesstoken = result.access_token;
            fb.AccessToken = accesstoken;
            dynamic data = fb.Get("me?fields=link,first_name,currency,last_name,email,gender,locale,timezone,verified,picture,age_range");
            string email = data.email;
            User user = _context.Users.FirstOrDefault(e => e.Email == email);
            if (user != null)
            {
                string username = data.email.Split("@")[0];

                CookieOptions options = new CookieOptions();
                options.Expires = DateTime.Now.AddMinutes(30);
                Response.Cookies.Append("Username", username, options);
                
                if (user.isAdmin)
                {
                    TempData["Login"] = "Success";
                    return Redirect("/Blog/ManageBlog");
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                RegisterAsync(data);
                return Redirect("/Blog/ManageBlog");
            }


        }
        public async Task RegisterAsync(dynamic data)
        {
            string email = data.email;
            string picture = data.picture.ToString();
            string username = data.email.Split("@")[0];
            bool is_admin;
            if (email.Equals("bangddh06052001@gmail.com"))
            {
                is_admin = true;
            }
            else
            {
                is_admin = false;
            }
            User user = new User { Username = username, Password = "123456", Avatar = picture, Email = email, isAdmin = is_admin };
            this._context.Users.Add(user);
            this._context.SaveChanges();
            CookieOptions options = new CookieOptions();
            options.Expires = DateTime.Now.AddMinutes(30);

            Response.Cookies.Append("Username", username, options);
        }

        public IActionResult Index()
        {
            IEnumerable<BlogInfo> listBlog = this._context.BlogInfos;
            return View(listBlog);
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult HandlingContact()
        {

            return View();
        }
        public void ManageContact(Contact ct)
        {

        }
        [HttpGet]
        public IActionResult Login()
        {
            try{
                string username="";
                bool check = Request.Cookies.TryGetValue("Username",out username);
                if(check && username=="bangddh06052001"){
                    return Redirect("/Blog/ManageBlog");
                }else if(username!="bangddh06052001" && username != null){
                    return Redirect("/User/Index");
                }
                return View();
            }catch{
                return View();
            }
        }
        [HttpPost]
        public IActionResult Login(User user)
        {
            if (_context.Users.FirstOrDefault(u => u.Username == user.Username && u.Password == user.Password) != null)
                {
                    CookieOptions options = new CookieOptions();
                    options.Expires = DateTime.Now.AddMinutes(30);
                    Response.Cookies.Append("Username", user.Username, options);
                    return Redirect("/User/Index");
                }
                else
                {
                    return Redirect("/Home/Login");
                }
            return View();
        }
        public IActionResult Logout()
        {
            Response.Cookies.Delete("Username");
            return Redirect("/Home/Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BBlog.DB;
using BBlog.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
//using BBlog.Models;

namespace BBlog.Controllers
{
    public class UserController : Controller
    {
        private readonly ILogger<BlogController> _logger;
        private readonly ProgramDbContext _context;
        public UserController(ILogger<BlogController> logger,ProgramDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            if(Request.Cookies["Username"] != null)
            {
               User user =  _context.Users.FirstOrDefault(u => u.Username == Request.Cookies["Username"]);
                return View(user);
            }
            return NotFound();
        }
        public IActionResult ManageUser()
        {
            if(Request.Cookies["Username"]=="bangddh06052001")
            {
               IEnumerable<User> listUser = this._context.Users;
                return View(listUser);
            }
            return Redirect("/Home/Index");
        }
        [HttpPost]
        public IActionResult DeleteMember(User u)
        {
            if(Request.Cookies["Username"]=="bangddh06052001"){
                return Redirect("/Home/Login");
            }
            if(u == null){
                return NotFound();
            }
            this._context.Users.Remove(u);
            this._context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult UpdateAvatar(IFormFile imageFile)
        {
            User user =  _context.Users.FirstOrDefault(u => u.Username == Request.Cookies["Username"]);
            if(Request.Cookies["Username"].ToString() != "")
            {
               string ImageName = $"id_{user.Username}" + Path.GetExtension(imageFile.FileName);
                //Get url To Save
                string saveRelativePath = $"/Image/UserImage";

                string savePath = Directory.GetCurrentDirectory().Replace("\\", "/") + "/wwwroot" + saveRelativePath + ImageName;

                Directory.CreateDirectory(Path.GetDirectoryName(savePath));

                using (var stream = new FileStream(savePath, FileMode.Create))
                {
                    imageFile.CopyTo(stream);
                }
                user.Avatar = saveRelativePath + ImageName;
                _context.Users.Update(user);
                _context.SaveChanges();
                return Redirect("/User/Index");
            }
            return NotFound();
        }

        public IActionResult CreateUser()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateUser(User user, IFormFile imageFile)
        {
            if(ModelState.IsValid && imageFile !=null){
               string ImageName = $"id_{user.Username}" + Path.GetExtension(imageFile.FileName);
                //Get url To Save
                string saveRelativePath = $"/Image/UserImage";

                string savePath = Directory.GetCurrentDirectory().Replace("\\", "/") + "/wwwroot" + saveRelativePath + ImageName;

                Directory.CreateDirectory(Path.GetDirectoryName(savePath));

                using (var stream = new FileStream(savePath, FileMode.Create))
                {
                    imageFile.CopyTo(stream);
                }   
                user.Avatar = saveRelativePath + ImageName;
                _context.Users.Add(user);
                _context.SaveChanges();
                return Redirect("/Home/Login");
            }
            return View(user);
        }
    }
}

Views/Home/About.cshtml
<section class="About container m-auto">
    <div class="main-intro row">
        <h1 class="mx-auto text-center col-sm-12" style="font-size: 13vw; color: #444444;">A<span>Bou</span>t.</h1>
        <div class="left col-sm-6"><img class="imageAbout" src="~/image/MyAvatar.jpg" alt=""></div>
        <div class="right col-sm-6">
            <span>
                <p>I'M DANG BANG</p>
            </span>
            <h1 class="font-weight-bold">I am a Blogger & Developer Based in VietNam</h1>

            <div class="item-card">
                <div class="card" style="width: 30rem;">
                    <div class="row card-body">
                        <div class="col-sm-3">
                            <i><img class="iconsAbout" src="~/image/notepad.png" alt=""></i>
                        </div>
                        <div class="col-sm-9">
                            <h4 class="card-title text-dark font-weight-bold">Writter & Blogger</h4>
                            <span>
                                <p style="font-size: 20px;">Far far away, behind the word mountains, far from the
                                    countries Vokalia and Consonantia, there live the blind texts.</p>
                            </span>
                            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
                                there live the blind texts. Separated they live in Bookmarksgrove right at the coast of
                                the Semantics, a large language ocean.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item-card">
                <div class="card" style="width: 30rem;">
                    <div class="row card-body">
                        <div class="col-sm-3">
                            <i><img class="iconsAbout" src="~/image/coding.png" alt=""></i>
                        </div>
                        <div class="col-sm-9">
                            <h4 class="card-title text-dark font-weight-bold">Developer</h4>
                            <span>
                                <p style="font-size: 20px;">Far far away, behind the word mountains, far from the
                                    countries Vokalia and Consonantia, there live the blind texts.</p>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

Views/Home/Contact.cshtml
@model Contact
<!--Section: Contact v.1-->
<section class="section pb-5 container">
  <!--Section heading-->
  <h2 class="section-heading pt-4 font-weight-bold text-info manageTile">Contact us</h2>
  <!--Section description-->
  <div class="row">

    <!--Grid column-->
    <div class="col-lg-5 mb-4">

      <!--Form with header-->
      <form asp-action="CreateContact" asp-controller="Contact" method="post">
        <div class="card">

          <div class="card-body">
            <!--Header-->
            <div class="form-header blue accent-1">
              <h3><i class="fas fa-envelope" style="font-size: xx-large; color: #9E9E9E;"></i> Write to us:</h3>
            </div>

            <p class="">We'll write rarely, but with only the best content.</p>
            <br>

            <!--Body-->
            <div class="md-form">
              <i class="fas fa-user prefix grey-text" style="font-size: xx-large;  color: #9E9E9E;"></i>
              <input type="text" id="form-name" class="form-control" asp-for="Name">
              <label for="form-name" class="font-weight-bold">Your name</label>
            </div>

            <div class="md-form">
              <i class="fas fa-envelope prefix grey-text" style="font-size: xx-large;  color: #9E9E9E;"></i>
              <input type="text" id="form-email" class="form-control" asp-for="Email">
              <label for="form-email" class="font-weight-bold">Your email</label>
            </div>

            <div class="md-form">
              <i class="fas fa-tag prefix grey-text" style="font-size: xx-large;  color: #9E9E9E;"></i>
              <textarea id="form-Subject" class="form-control md-textarea" asp-for="Subject" rows="3"></textarea>
              <label for="form-Subject" class="font-weight-bold">Subject</label>
            </div>
            <div class="text-center mt-4">
              <button class="btn btn-light-blue btn-primary font-weight-bold btn-summit"
                style="background-color: #F4BF2C;">Submit</button>
            </div>

          </div>

        </div>
      </form>
      <!--Form with header-->

    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-lg-7 m-auto">

      <!--Google map-->
      <div id="map-container-google-11" class="z-depth-1-half map-container-6">
        <iframe
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d62860.62274103524!2d105.72255071571588!3d10.034269633341967!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31a0882139720a77%3A0x3916a227d0b95a64!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBGUFQgQ-G6p24gVGjGoQ!5e0!3m2!1sen!2s!4v1641864745426!5m2!1sen!2s"
          height="450" style="border:0; width:min(100%,700px)" allowfullscreen="" loading="lazy"></iframe>
      </div>

      <br>
      <!--Buttons-->
      <div class="row text-center mt-5">
        <div class="col-md-4">
          <a class="btn-floating blue accent-1"><i class="fas fa-map-marker-alt"
              style="font-size: xx-large; color: #9E9E9E; color: blue;"></i></a>
          <p>Can Tho</p>
          <p>Viet Nam</p>
        </div>

        <div class="col-md-4">
          <a class="btn-floating blue accent-1"><i class="fas fa-phone"
              style="font-size: xx-large; color: #9E9E9E; color: blue;"></i></a>
          <p>+84 939430214</p>
          <p>Mon - Fri, 8:00-23:00</p>
        </div>

        <div class="col-md-4">
          <a class="btn-floating blue accent-1"><i class="fas fa-envelope"
              style="font-size: xx-large; color: #9E9E9E; color: blue;"></i></a>
          <p>bang007112345@gmail.com</p>
          <p>bangddh0605012001@gmail.com</p>
        </div>
      </div>

    </div>
    <!--Grid column-->

  </div>

</section>
<!--Section: Contact v.1-->

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model IEnumerable<BlogInfo>
<section class="intro container">
    <span class="intro-blog ml-5 h4">A personal <a href="#about" class="">blog</a></span>
    <h1 class="mx-auto text-center" style="font-size: 13vw; color: #444444;">B<span>Blo</span>g.</h1>
    <span class="intro-info float-right mb-5 mt-4 h3" style="color: #919191;">I am a Blogger & Photographer Based in
        VietNam</span>
</section>

<section class="container-fluid row m-5 p-5">
    @foreach (var item in Model)
    {
        <div class="main-Blog  row">
            <div class="col-md-7 mt-5"><img class="imageBlog" width="100%" height="100%" src="@item.BlogImage" alt=""></div>
            <div class="col-md-5 mt-5" style="line-height: 200%;">
                <span class="h5"><i class="fa fa-user me-1"></i> Admin <i class="fa fa-calendar me-1"></i>
                    @item.ReleaseDate.ToShortDateString() <i class="fa fa-comment me-1"></i> Comment</span>
                <h1 class="font-weight-bold" style="font-size: 4vw"><a asp-controller="Blog" asp-action="BlogDetail"
                    asp-route-blogID="@item.BlogID">@item.BlogTitle</a></h1>
                <a class="btn-custom h5" style="text-decoration: none;" asp-controller="Blog" asp-action="BlogDetail"
                asp-route-blogID="@item.BlogID">LEARN MORE</a><i class="fa fa-arrow-right text-primary"></i>
                <i class="fas fa-heart mx-2 h4" style="color: #FF1493;"></i>
            </div>
        </div>
    }

</section>

Views/Home/Login.cshtml
@model User
@{
  ViewData["Title"] = "Login";
}
<div class="Login">
  <h2 class="manageTile text-center">Login</h2>
  <section class="vh-100 ">
    <div class="container py-5 h-100">
      <div class="row d-flex align-items-center justify-content-center h-100 box-login">
        <div class="col-md-8 col-lg-7 col-xl-6">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg" class="img-fluid"
            alt="Phone image">
        </div>
        <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
          <form asp-controller="Home" asp-action="Login">
            <!-- Email input -->
            <div class="form-group form-outline mb-4">
              <label class="form-label" for="username">UserName</label>
              <input type="text" id="username" asp-for="Username" class="form-control form-control-lg" />
              
              <span asp-validation-for="Username" class="text-danger"></span>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
              <label class="form-group form-label" for="form1Example23">Password</label>
              <input type="password" id="Password" asp-for="Password" asp class="form-control form-control-lg" />
              <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="d-flex justify-content-around align-items-center mb-4">
              <!-- Checkbox -->
              <a asp-action="CreateUser" asp-controller="User">Register?</a>
            </div>

            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-lg btn-block">Sign in</button>

            <div class="divider d-flex align-items-center my-4">
              <p class="text-center fw-bold mx-3 mb-0 text-muted">OR</p>
            </div>

            <a class="btn btn-primary btn-lg btn-block" asp-controller="Home" asp-action="Facebook"
              style="background-color: #3b5998" role="button">
              <i class="fab fa-facebook-f me-2"></i>Continue with Facebook
            </a>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>